init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v3.0.$env:APPVEYOR_BUILD_NUMBER" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

environment:
  matrix:
  - job_name: Windows x64 Build
    platform: x64
    appveyor_build_worker_image: Visual Studio 2022
    configuration: ReleaseWindows
  - job_name: Windows x86 Build
    platform: x86
    appveyor_build_worker_image: Visual Studio 2022
    configuration: ReleaseWindows
  - job_name: Windows ARM64 Build
    platform: ARM64
    appveyor_build_worker_image: Visual Studio 2022
    configuration: ReleaseWindows

  BugsplatDatabase: sjofnllc
  PfxDownloadUrl:
    secure: T8uKu+tTR2G7LDE1zPGNOi+prl4YaKXP6DOC5eU6A14FEQkd8PFR3nQ1WMwryphJ
  PfxDownloadPasswd:
    secure: nAIqrjhaoamhiuAcae/xNw==
  PfxPassword:
    secure: +vWSGzLkiBGVIxfPb+iRtD+/maQjI2d92hN4PoNAxMc=
  SPARKLE_PRIVATE_KEY:
    secure: 2g7T+W5R3tcNVfzj5/dXfUqk17KbTwmVQY9RIFYpGHD/xH32T0Tq6C5zzsDkWXtE
  SPARKLE_PUBLIC_KEY: euvj+Uut3Nt3BVIu+aqJ02++Jflh8VjzBUzMgb7EnP8=

branches:
  except:
    - localbuilding

pull_requests:
  do_not_increment_build_number: true

install:
  - ps: dotnet tool install --global NetSparkleUpdater.Tools.AppCastGenerator

build:
  project: radegast.sln
  parallel: true
  verbosity: minimal

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

before_build:
  - nuget restore radegast.sln

after_build:
  - ps: New-Item -ItemType directory -Path .\$env:PLATFORM
  - cmd: '7z a -ttar -so Radegast-%TAG_VERSION%.tar %APPVEYOR_BUILD_FOLDER%\bin\Release\ | 7z a -si Radegast_%PLATFORM%-%TAG_VERSION%.tbz'
  - ps: Copy-Item bin\Packages\en-US\RadegastSetup_$env:PLATFORM.msi RadegastSetup_$env:PLATFORM-$env:TAG_VERSION.msi
  - ps: Copy-Item bin\Packages\RadegastBundle_$env:PLATFORM.exe RadegastSetup_$env:PLATFORM-$env:TAG_VERSION.exe
  - ps: netsparkle-generate-appcast -n Radegast -e "exe,msi" -a . --output-type json -o windows-$env:PLATFORM --file-version $env:APPVEYOR_REPO_TAG -u https://github.com/cinderblocks/radegast/releases/download/tag/$env:APPVEYOR_REPO_TAG

artifacts:
  - path: 'RadegastSetup*.exe'
    name: 'Radegast Windows x64 Bundle'
    type: Auto
  - path: 'RadegastSetup*.msi'
    name: 'Radegast Windows x64 MSI'
    type: Auto
  - path: 'Radegast*.tbz'
    name: 'Radegast Linux x64'
    type: Auto
  - path: 'RadegastSetup*.exe'
    name: 'Radegast Windows x86 Bundle'
    type: Auto
  - path: 'RadegastSetup*.msi'
    name: 'Radegast Windows x86 MSI'
    type: Auto
  - path: 'Radegast-*.tbz'
    name: 'Radegast Linux x86'
    type: Auto
  - path: 'bin\Release\Radegast.pdb'
    name: 'Radegast symbols'
    type: Auto
  - path: 'appcast.json'
    name: AppCast
    type: Auto
  - path: 'appcast.json.signature'
    name: AppCast Signature
    type: Auto
